name: Build and Deploy

on:
  push:
    branches:
      - main  # 只在 main 分支發生推送時執行流水線，可以根據您的需求調整

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 環境執行作業，您也可以選擇其他適合的 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 取得程式碼

      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true # 使用 Maven 執行打包

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Docker 上下文路徑，此處使用專案根目錄
          push: false  # 是否推送映像到 Docker Hub，此處先設為 false，稍後再推送

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Docker 上下文路徑，此處使用專案根目錄
          push: true   # 現在將推送 Docker 映像至 Docker Hub
          tags: ${{ secrets.DOCKER_NAMESPACE }}/docker-spring-demo:${{github.sha}}  # 修改成您的 Docker Hub 用戶名和映像名稱

